; IconPointers indexes (see data/icon_pointers.asm)
	const_def
	const ICON_NULL
	; const ICON_POLIWAG
	const ICON_DIGLETT
	; const ICON_BUG
	; const ICON_EQUINE
	; const ICON_VOLTORB
	const ICON_EGG
	; const ICON_MOTH
	; const ICON_BAT
	const ICON_BULBASAUR
	const ICON_CHARMANDER
	const ICON_CHARIZARD
	const ICON_SQUIRTLE
	const ICON_CATERPILLAR
	const ICON_KAKUNA
	const ICON_VIVILLON
	const ICON_BEEDRILL
	const ICON_RATTATA
	const ICON_PIKACHU
	const ICON_MONSTER
	const ICON_NIDORAN_F
	const ICON_CLEFAIRY
	const ICON_FOX
	const ICON_JIGGLYPUFF
	const ICON_ZUBAT
	const ICON_ODDISH
	const ICON_GRUBBIN
	const ICON_MEOWTH
	const ICON_PSYDUCK
	const ICON_ABRA
	const ICON_ALAKAZAM
	const ICON_FIGHTER
	const ICON_VICTREEBEL
	const ICON_JELLYFISH
	const ICON_GEODUDE
	const ICON_PONYTA
	const ICON_SLOWPOKE
	const ICON_MAGNEMITE
	const ICON_FARFETCH_D
	const ICON_SEEL
	const ICON_BLOB
	const ICON_DITTO
	const ICON_SHELL
	const ICON_GASTLY
	const ICON_GHOST
	const ICON_SERPENT
	const ICON_HUMANSHAPE
	const ICON_KRABBY
	const ICON_SUDOWOODO
	const ICON_CHANSEY
	const ICON_TANGELA
	const ICON_HORSEA
	const ICON_STARYU
	const ICON_SCYTHER
	; const ICON_BIGMON
	const ICON_TAUROS
	const ICON_FISH
	const ICON_GYARADOS
	const ICON_LAPRAS
	const ICON_EEVEE
	const ICON_PORYGON2
	const ICON_SNORLAX
	const ICON_ARTICUNO
	const ICON_ZAPDOS
	const ICON_MOLTRES
	const ICON_MEWTWO
	const ICON_MEW
	const ICON_TANGEL
	const ICON_BEAR
	const ICON_WOLFROST
	const ICON_CHIKORITA
	const ICON_MEGANIUM
	const ICON_CYNDAQUIL
	const ICON_TYPHLOSION
	const ICON_TOTODILE
	const ICON_FERALIGATR
	const ICON_SENTRET
	const ICON_BIRD
	const ICON_LEDIAN
	const ICON_JOLTIK
	const ICON_CHINCHOU
	const ICON_TOGEPI
	const ICON_FLAAFFY
	const ICON_YANMA
	const ICON_UNOWN
	const ICON_GIRAFARIG
	const ICON_FERROSEED
	const ICON_DUNSPARCE
	const ICON_GLIGAR
	const ICON_SHUCKLE
	const ICON_SNEASEL
	const ICON_SLUGMA
	const ICON_SWINUB
	const ICON_CORSOLA
	const ICON_OCTILLERY
	const ICON_MANTINE
	const ICON_DONPHAN
	const ICON_MILTANK
	const ICON_RAIKOU
	const ICON_ENTEI
	const ICON_SUICUNE
	const ICON_LUGIA
	const ICON_HO_OH
	const ICON_CELEBI
	const ICON_TREECKO
	const ICON_SCEPTILE
	const ICON_TORCHIC
	const ICON_BLAZIKEN
	const ICON_MUDKIP
	const ICON_SWAMPERT
	const ICON_ZIGZAGOON
	const ICON_LOTAD
	const ICON_WINGULL
	const ICON_GARDEVOIR
	const ICON_SHROOMISH
	const ICON_MAKUHITA
	const ICON_NOSEPASS
	const ICON_MAWILE
	const ICON_ROSELIA
	const ICON_WAILMER
	const ICON_NUMEL
	const ICON_ALTARIA
	const ICON_CARBINK
	const ICON_BALTOY
	const ICON_CHIMECHO
	const ICON_SNORUNT
	const ICON_TYRUNT
	const ICON_SHELGON
	; const ICON_METANG
	; const ICON_REGI
	const ICON_LATIAS
	; const ICON_KYOGRE
	const ICON_GROUDON
	; const ICON_RAYQUAZA
	; const ICON_JIRACHI
	const ICON_DEOXYS
	const ICON_TURTWIG
	const ICON_CHIMCHAR
	const ICON_PIPLUP
	const ICON_DRIFLOON
	const ICON_CHINGLING
	const ICON_BRONZOR
	const ICON_HAXORUS
	const ICON_LUCARIO
	const ICON_CROAGUNK
	; const ICON_MESPRIT
	const ICON_AURORUS
	; const ICON_SHAYMIN
	const ICON_ARCEUS
	const ICON_ROCKRUFF
	const ICON_VENONAT
	const ICON_MANKEY
	const ICON_EXEGGCUTE
	const ICON_KOFFING
	const ICON_ELECTABUZZ
	const ICON_VIKAVOLT
	const ICON_OMANYTE
	const ICON_LUVDISC
	const ICON_SHARPEDO
	const ICON_HOOTHOOT
	const ICON_MAREEP
	const ICON_AMPHAROS
	const ICON_MARILL
	const ICON_WOOPER
	const ICON_QUAGSIRE
	const ICON_MURKROW
	const ICON_SHUPPET
	const ICON_GRANBULL
	const ICON_HERACROSS
	const ICON_PHANPY
	const ICON_SMEARGLE
	const ICON_LARVITAR
	const ICON_PUPITAR
	const ICON_TYRANITAR
	const ICON_PELIPPER
	const ICON_ARON
	; const ICON_TORKOAL
	; const ICON_GRUMPIG
	const ICON_TRAPINCH
	const ICON_FLYGON
	const ICON_ZANGOOSE
	const ICON_LUNATONE
	const ICON_SOLROCK
	const ICON_CLAYDOL
	const ICON_LILEEP
	const ICON_DUSKULL
	const ICON_DUSCLOPS
	const ICON_TROPIUS
	const ICON_ABSOL
	const ICON_GLALIE
	const ICON_SPHEAL
	const ICON_SALAMENCE
	; const ICON_BELDUM
	; const ICON_METAGROSS
	const ICON_FLOATZEL
	const ICON_BRONZONG
	const ICON_TOGEKISS
	const ICON_DEWOTT
	const ICON_MUNNA
	const ICON_SCOLIPEDE
	const ICON_KROOKODILE
	; const ICON_ARCHEN
	const ICON_SOLOSIS
	const ICON_LITWICK
	const ICON_CHANDELURE
	const ICON_AXEW
	; const ICON_GOLURK
	const ICON_HEATMOR
	; const ICON_DEINO
	; const ICON_ZWEILOUS
	; const ICON_HYDREIGON
	const ICON_SPEWPA
	; const ICON_VOLCARONA
	const ICON_CHESPIN
	const ICON_CHESNAUGHT
	const ICON_FENNEKIN
	const ICON_DELPHOX
	const ICON_FROAKIE
	const ICON_GRENINJA
	const ICON_FLOETTE
	const ICON_GOGOAT
	const ICON_ESPURR
	const ICON_HONEDGE
	const ICON_INKAY
	const ICON_DEDENNE
	const ICON_GOODRA
	; const ICON_KLEFKI
	const ICON_BERGMITE
	; const ICON_XERNEAS
	; const ICON_YVELTAL
	; const ICON_ZYGARDE
	; const ICON_VOLCANION
	const ICON_ROWLET
	const ICON_DECIDUEYE
	const ICON_RIBOMBEE
	const ICON_SNIVY
	const ICON_MUDSDALE
	const ICON_MORELULL
	const ICON_AIPOM
	const ICON_SANDYGAST
	const ICON_PYUKUMUKU
	; const ICON_TYPE_NULL
	; const ICON_SILVALLY
	const ICON_TOGEDEMARU
	const ICON_DHELMISE
	; const ICON_HAKAMO_O
	; const ICON_NIHILEGO
	; const ICON_BUZZWOLE
	; const ICON_PHEROMOSA
	; const ICON_XURKITREE
	; const ICON_CELESTEELA
	; const ICON_KARTANA
	; const ICON_GUZZLORD
	; const ICON_MAGEARNA
	; const ICON_STAKATAKA
	; const ICON_BLACEPHALON
	const ICON_APPLIN
	const ICON_SIZZLIPEDE
	const ICON_CLOBBOPUS
	const ICON_POLTEAGEIST
	const ICON_BLASTOISE
	const ICON_SANDSHREW
	const ICON_NIDOKING
	const ICON_DODUO
	const ICON_CUBONE
	const ICON_RHYHORN
	const ICON_MAGMAR
	const ICON_PINSIR
	const ICON_FURRET
	const ICON_TOGETIC
	const ICON_MISDREAVUS
	const ICON_WOBBUFFET
	const ICON_SKARMORY
	const ICON_STANTLER
	const ICON_SHIFTRY
	const ICON_RALTS
	const ICON_MASQUERAIN
	const ICON_GULPIN
	const ICON_MILOTIC
	const ICON_WALREIN
	const ICON_PIGNITE
	; const ICON_TYNAMO
	const ICON_ELGYEM
	const ICON_LAMPENT
	const ICON_MIENSHAO
	; const ICON_DRUDDIGON
	const ICON_FLETCHLING
	; const ICON_FLABEBE
	const ICON_FLORGES
	const ICON_SPRITZEE
	const ICON_AROMATISSE
	const ICON_HAWLUCHA
	const ICON_PUMPKABOO
	const ICON_GOURGEIST
	const ICON_ORANGURU
NUM_ICONS EQU const_value - 1

; LoadMenuMonIcon.Jumptable indexes (see engine/gfx/mon_icons.asm)
	const_def
	const MONICON_PARTYMENU
	const MONICON_NAMINGSCREEN
	const MONICON_MOVES
	const MONICON_TRADE
	const MONICON_MOBILE1
	const MONICON_MOBILE2
	const MONICON_UNUSED
	const MONICON_POKEDEX

; party menu icon palettes
	const_def
	const PAL_ICON_RED    ; 0
	const PAL_ICON_BLUE   ; 1
	const PAL_ICON_GREEN  ; 2
	const PAL_ICON_BROWN  ; 3
	const PAL_ICON_PINK   ; 4
	const PAL_ICON_GRAY   ; 5
	const PAL_ICON_GOLD   ; 6
	const PAL_ICON_PURPLE ; 7
