; item ids
; indexes for:
; - ItemNames (see data/items/names.asm)
; - ItemDescriptions (see data/items/descriptions.asm)
; - ItemAttributes (see data/items/attributes.asm)
; - ItemEffects (see engine/items/item_effects.asm)
	const_def
	const NO_ITEM      ; 00
	const MASTER_BALL  ; 01
	const ULTRA_BALL   ; 02
	const GREAT_BALL   ; 03
	const POKE_BALL    ; 04
	const HEAVY_BALL   ; 05
	const LEVEL_BALL   ; 06
	const LURE_BALL    ; 07
	const FAST_BALL    ; 08
	const FRIEND_BALL  ; 09
	const MOON_BALL    ; 0a
	const LOVE_BALL    ; 0b
	const DUSK_BALL    ; 0c
	const DREAM_BALL   ; 0d
	const REPEAT_BALL  ; 0e
	const TIMER_BALL   ; 0f
	const QUICK_BALL   ; 10
	const NET_BALL     ; 11
	const PARK_BALL    ; 12
	const TOWN_MAP     ; 13
	const BICYCLE      ; 14
	const ESCAPE_ROPE  ; 15
	const COIN_CASE    ; 16
	const ITEMFINDER   ; 17
	const POKE_FLUTE   ; 18
	const OLD_ROD      ; 19
	const GOOD_ROD     ; 1a
	const SUPER_ROD    ; 1b
	const RED_SCALE    ; 1c
	const SECRETPOTION ; 1d
	const S_S_TICKET   ; 1e
	const MYSTERY_EGG  ; 1f
	const CLEAR_BELL   ; 20
	const SILVER_WING  ; 21
	const GS_BALL      ; 22
	const BLUE_CARD    ; 23
	const CARD_KEY     ; 24
	const MACHINE_PART ; 25
	const EGG_TICKET   ; 26
	const LOST_ITEM    ; 27
	const BASEMENT_KEY ; 28
	const PASS         ; 29
	const SQUIRTBOTTLE ; 2a
	const RAINBOW_WING ; 2b
	const MOON_STONE   ; 2c
	const FIRE_STONE   ; 2d
	const THUNDERSTONE ; 2e
	const WATER_STONE  ; 2f
	const LEAF_STONE   ; 30
	const SUN_STONE    ; 31
	const HEART_STONE  ; 32
	const ICE_STONE    ; 33
	const DAWN_STONE   ; 34
	const DUSK_STONE   ; 35
	const SHINY_STONE  ; 36
	const TART_APPLE   ; 37
	const SWEET_APPLE  ; 38
	const CRACKED_POT  ; 39
	const ANTIDOTE     ; 3a
	const BURN_HEAL    ; 3b
	const ICE_HEAL     ; 3c
	const AWAKENING    ; 3d
	const PARLYZ_HEAL  ; 3e
	const FULL_HEAL    ; 3f
	const FULL_RESTORE ; 40
	const MAX_POTION   ; 41
	const HYPER_POTION ; 42
	const SUPER_POTION ; 43
	const POTION       ; 44
	const ETHER        ; 45
	const MAX_ETHER    ; 46
	const ELIXER       ; 47
	const MAX_ELIXER   ; 48
	const HP_UP        ; 49
	const PROTEIN      ; 4a
	const IRON         ; 4b
	const CARBOS       ; 4c
	const CALCIUM      ; 4d
	const ZINC         ; 4e
	const PP_UP        ; 4f
	const RARE_CANDY   ; 50
	const REVIVE       ; 51
	const MAX_REVIVE   ; 52
	const FRESH_WATER  ; 53
	const SODA_POP     ; 54
	const LEMONADE     ; 55
	const MOOMOO_MILK  ; 56
	const RAGECANDYBAR ; 57
	const BERRY_JUICE  ; 58
	const LAVA_COOKIE  ; 59
	const ENERGYPOWDER ; 5a
	const ENERGY_ROOT  ; 5b
	const HEAL_POWDER  ; 5c
	const REVIVAL_HERB ; 5d
	const SACRED_ASH   ; 5e
	const REPEL        ; 5f
	const SUPER_REPEL  ; 60
	const MAX_REPEL    ; 61
	const HONEY        ; 62
	const X_ACCURACY   ; 63
	const X_ATTACK     ; 64
	const X_DEFEND     ; 65
	const X_SPEED      ; 66
	const X_SP_ATK     ; 67
	const X_SP_DEF     ; 68
	const POKE_DOLL    ; 69
	const GUARD_SPEC   ; 6a
	const DIRE_HIT     ; 6b
	const NUGGET       ; 6c
	const BIG_NUGGET   ; 6d
	const SILVER_LEAF  ; 6e
	const GOLD_LEAF    ; 6f
	const TINYMUSHROOM ; 70
	const BIG_MUSHROOM ; 71
	const SLOWPOKETAIL ; 72
	const PEARL        ; 73
	const BIG_PEARL    ; 74
	const STARDUST     ; 75
	const STAR_PIECE   ; 76
	const BRICK_PIECE  ; 77
	const PRETTY_WING  ; 78
	const COMET_SHARD  ; 79
	const HEART_SCALE  ; 7a
	const FLOWER_MAIL  ; 7b
	const SURF_MAIL    ; 7c
	const LITEBLUEMAIL ; 7d
	const PORTRAITMAIL ; 7e
	const LOVELY_MAIL  ; 7f
	const EON_MAIL     ; 80
	const MORPH_MAIL   ; 81
	const BLUESKY_MAIL ; 82
	const MUSIC_MAIL   ; 83
	const MIRAGE_MAIL  ; 84
	const BRIGHTPOWDER ; 85
	const LUCKY_PUNCH  ; 86
	const METAL_POWDER ; 87
	const EXP_SHARE    ; 88
	const QUICK_CLAW   ; 89
	const KINGS_ROCK   ; 8a
	const AMULET_COIN  ; 8b
	const CLEANSE_TAG  ; 8c
	const STICK        ; 8d
	const SMOKE_BALL   ; 8e
	const EVERSTONE    ; 8f
	const THICK_CLUB   ; 90
	const FOCUS_BAND   ; 91
	const LUCKY_EGG    ; 92
	const SCOPE_LENS   ; 93
	const LEFTOVERS    ; 94
	const SEA_SCALE    ; 95
	const BERSERK_GENE ; 96
	const LIGHT_BALL   ; 97
	const EVIOLITE     ; 98
	const BLACK_SLUDGE ; 99
	const LIGHT_CLAY   ; 9a
	const GRIP_CLAW    ; 9b
	const POWER_HERB   ; 9c
	const HEAT_ROCK    ; 9d
	const DAMP_ROCK    ; 9e
	const SMOOTH_ROCK  ; 9f
	const ICY_ROCK     ; a0
	const UP_GRADE     ; a1
	const OVAL_STONE   ; a2
	const RAZOR_FANG   ; a3
	const RAZOR_CLAW   ; a4
	const ELECTIRIZER  ; a5
	const DUBIOUS_DISC ; a6
	const REAPER_CLOTH ; a7
	const WHIPPEDDREAM ; a8
	const SACHET       ; a9
	const BERRY_SWEET  ; aa
	const SOFT_SAND    ; ab
	const SHARP_BEAK   ; ac
	const POISON_BARB  ; ad
	const SILVERPOWDER ; ae
	const MYSTIC_WATER ; af
	const TWISTEDSPOON ; b0
	const BLACKBELT    ; b1
	const BLACKGLASSES ; b2
	const PINK_BOW     ; b3
	const NEVERMELTICE ; b4
	const MAGNET       ; b5
	const SPELL_TAG    ; b6
	const MIRACLE_SEED ; b7
	const HARD_STONE   ; b8
	const CHARCOAL     ; b9
	const METAL_COAT   ; ba
	const DRAGON_FANG  ; bb
	const POLKADOT_BOW ; bc
	const PSNCUREBERRY ; bd
	const PRZCUREBERRY ; be
	const BURNT_BERRY  ; bf
	const ICE_BERRY    ; c0
	const BITTER_BERRY ; c1
	const MINT_BERRY   ; c2
	const MIRACLEBERRY ; c3
	const MYSTERYBERRY ; c4
	const BERRY        ; c5
	const GOLD_BERRY   ; c6
	const LIECHI_BERRY ; c7
	const GANLON_BERRY ; c8
	const SALAC_BERRY  ; c9
	const PETAYA_BERRY ; ca
	const APICOT_BERRY ; cb
	const MICLE_BERRY  ; cc
	const GINEMA_BERRY ; cd
	const RED_APRICORN ; ce
	const BLU_APRICORN ; cf
	const YLW_APRICORN ; d0
	const GRN_APRICORN ; d1
	const WHT_APRICORN ; d2
	const BLK_APRICORN ; d3
	const PNK_APRICORN ; d4
	const NORMAL_BOX   ; d5
	const GORGEOUS_BOX ; d6
	const BLUE_FLUTE   ; d7
	const YELLOW_FLUTE ; d8
	const RED_FLUTE    ; d9
	const ITEM_DA      ; da
	const ITEM_DB      ; db
	const ITEM_DC      ; dc
	const ITEM_DD      ; dd
	const ITEM_DE      ; de
	const ITEM_DF      ; df
	const ITEM_E0      ; e0
	const ITEM_E1      ; e1
	const ITEM_E2      ; e2
	const ITEM_E3      ; e3
	const ITEM_E4      ; e4
	const ITEM_E5      ; e5
	const ITEM_E6      ; e6
	const ITEM_E7      ; e7
	const ITEM_E8      ; e8
	const ITEM_E9      ; e9
	const ITEM_EA      ; ea
	const ITEM_EB      ; eb
	const ITEM_EC      ; ec
	const ITEM_ED      ; ed
	const ITEM_EE      ; ee
	const ITEM_EF      ; ef
	const ITEM_F0      ; f0
	const ITEM_F1      ; f1
	const ITEM_F2      ; f2
	const ITEM_F3      ; f3
	const ITEM_F4      ; f4
	const ITEM_F5      ; f5
	const ITEM_F6      ; f6
	const ITEM_F7      ; f7
	const ITEM_F8      ; f8
	const ITEM_F9      ; f9
	const ITEM_FA      ; fa
	const ITEM_FB      ; fb
	const ITEM_FC      ; fc
	const ITEM_FD      ; fd
	const ITEM_FE      ; fe
NUM_ITEMS EQU const_value - 1

USE_SCRIPT_VAR EQU $00
ITEM_FROM_MEM  EQU $ff

; leftovers from red
SAFARI_BALL    EQU $08 ; MOON_STONE
MOON_STONE_RED EQU $0a ; BURN_HEAL
FULL_HEAL_RED  EQU $34 ; X_SPEED
