; item ids
; indexes for:
; - ItemNames (see data/items/names.asm)
; - ItemDescriptions (see data/items/descriptions.asm)
; - ItemAttributes (see data/items/attributes.asm)
; - ItemEffects (see engine/items/item_effects.asm)
	const_def
	const NO_ITEM      ; 00
	const MASTER_BALL  ; 01
	const ULTRA_BALL   ; 02
	const GREAT_BALL   ; 03
	const POKE_BALL    ; 04
	const HEAVY_BALL   ; 05
	const LEVEL_BALL   ; 06
	const LURE_BALL    ; 07
	const FAST_BALL    ; 08
	const FRIEND_BALL  ; 09
	const MOON_BALL    ; 0a
	const LOVE_BALL    ; 0b
	const DUSK_BALL    ; 0c
	const PARK_BALL    ; 0d
	const TOWN_MAP     ; 0e
	const BICYCLE      ; 0f
	const ESCAPE_ROPE  ; 10
	const COIN_CASE    ; 11
	const ITEMFINDER   ; 12
	const POKE_FLUTE   ; 13
	const OLD_ROD      ; 14
	const GOOD_ROD     ; 15
	const SUPER_ROD    ; 16
	const RED_SCALE    ; 17
	const SECRETPOTION ; 18
	const S_S_TICKET   ; 19
	const MYSTERY_EGG  ; 1a
	const CLEAR_BELL   ; 1b
	const SILVER_WING  ; 1c
	const GS_BALL      ; 1d
	const BLUE_CARD    ; 1e
	const CARD_KEY     ; 1f
	const MACHINE_PART ; 20
	const EGG_TICKET   ; 21
	const LOST_ITEM    ; 22
	const BASEMENT_KEY ; 23
	const PASS         ; 24
	const SQUIRTBOTTLE ; 25
	const RAINBOW_WING ; 26
	const MOON_STONE   ; 27
	const FIRE_STONE   ; 28
	const THUNDERSTONE ; 29
	const WATER_STONE  ; 2a
	const LEAF_STONE   ; 2b
	const SUN_STONE    ; 2c
	const HEART_STONE  ; 2d
	const ICE_STONE    ; 2e
	const DAWN_STONE   ; 2f
	const DUSK_STONE   ; 30
	const SHINY_STONE  ; 31
	const TART_APPLE   ; 32
	const SWEET_APPLE  ; 33
	const CRACKED_POT  ; 34
	const ANTIDOTE     ; 35
	const BURN_HEAL    ; 36
	const ICE_HEAL     ; 37
	const AWAKENING    ; 38
	const PARLYZ_HEAL  ; 39
	const FULL_HEAL    ; 3a
	const FULL_RESTORE ; 3b
	const MAX_POTION   ; 3c
	const HYPER_POTION ; 3d
	const SUPER_POTION ; 3e
	const POTION       ; 3f
	const ETHER        ; 40
	const MAX_ETHER    ; 41
	const ELIXER       ; 42
	const MAX_ELIXER   ; 43
	const HP_UP        ; 44
	const PROTEIN      ; 45
	const IRON         ; 46
	const CARBOS       ; 47
	const CALCIUM      ; 48
	const ZINC         ; 49
	const PP_UP        ; 4a
	const RARE_CANDY   ; 4b
	const REVIVE       ; 4c
	const MAX_REVIVE   ; 4d
	const FRESH_WATER  ; 4e
	const SODA_POP     ; 4f
	const LEMONADE     ; 50
	const MOOMOO_MILK  ; 51
	const RAGECANDYBAR ; 52
	const BERRY_JUICE  ; 53
	const LAVA_COOKIE  ; 54
	const ENERGYPOWDER ; 55
	const ENERGY_ROOT  ; 56
	const HEAL_POWDER  ; 57
	const REVIVAL_HERB ; 58
	const SACRED_ASH   ; 59
	const REPEL        ; 5a
	const SUPER_REPEL  ; 5b
	const MAX_REPEL    ; 5c
	const HONEY        ; 5d
	const X_ACCURACY   ; 5e
	const X_ATTACK     ; 5f
	const X_DEFEND     ; 60
	const X_SPEED      ; 61
	const X_SP_ATK     ; 62
	const X_SP_DEF     ; 63
	const POKE_DOLL    ; 64
	const GUARD_SPEC   ; 65
	const DIRE_HIT     ; 66
	const NUGGET       ; 67
	const BIG_NUGGET   ; 68
	const SILVER_LEAF  ; 69
	const GOLD_LEAF    ; 6a
	const TINYMUSHROOM ; 6b
	const BIG_MUSHROOM ; 6c
	const SLOWPOKETAIL ; 6d
	const PEARL        ; 6e
	const BIG_PEARL    ; 6f
	const STARDUST     ; 70
	const STAR_PIECE   ; 71
	const BRICK_PIECE  ; 72
	const PRETTY_WING  ; 73
	const COMET_SHARD  ; 74
	const FLOWER_MAIL  ; 75
	const SURF_MAIL    ; 76
	const LITEBLUEMAIL ; 77
	const PORTRAITMAIL ; 78
	const LOVELY_MAIL  ; 79
	const EON_MAIL     ; 7a
	const MORPH_MAIL   ; 7b
	const BLUESKY_MAIL ; 7c
	const MUSIC_MAIL   ; 7d
	const MIRAGE_MAIL  ; 7e
	const BRIGHTPOWDER ; 7f
	const LUCKY_PUNCH  ; 80
	const METAL_POWDER ; 81
	const EXP_SHARE    ; 82
	const QUICK_CLAW   ; 83
	const KINGS_ROCK   ; 84
	const AMULET_COIN  ; 85
	const CLEANSE_TAG  ; 86
	const STICK        ; 87
	const SMOKE_BALL   ; 88
	const EVERSTONE    ; 89
	const THICK_CLUB   ; 8a
	const FOCUS_BAND   ; 8b
	const LUCKY_EGG    ; 8c
	const SCOPE_LENS   ; 8d
	const LEFTOVERS    ; 8e
	const SEA_SCALE    ; 8f
	const BERSERK_GENE ; 90
	const LIGHT_BALL   ; 91
	const EVIOLITE     ; 92
	const BLACK_SLUDGE ; 93
	const UP_GRADE     ; 94
	const OVAL_STONE   ; 95
	const RAZOR_FANG   ; 96
	const RAZOR_CLAW   ; 97
	const ELECTIRIZER  ; 98
	const DUBIOUS_DISC ; 99
	const REAPER_CLOTH ; 9a
	const WHIPPEDDREAM ; 9b
	const SACHET       ; 9c
	const BERRY_SWEET  ; 9d
	const SOFT_SAND    ; 9e
	const SHARP_BEAK   ; 9f
	const POISON_BARB  ; a0
	const SILVERPOWDER ; a1
	const MYSTIC_WATER ; a2
	const TWISTEDSPOON ; a3
	const BLACKBELT    ; a4
	const BLACKGLASSES ; a5
	const PINK_BOW     ; a6
	const NEVERMELTICE ; a7
	const MAGNET       ; a8
	const SPELL_TAG    ; a9
	const MIRACLE_SEED ; aa
	const HARD_STONE   ; ab
	const CHARCOAL     ; ac
	const METAL_COAT   ; ad
	const DRAGON_FANG  ; ae
	const POLKADOT_BOW ; af
	const PSNCUREBERRY ; b0
	const PRZCUREBERRY ; b1
	const BURNT_BERRY  ; b2
	const ICE_BERRY    ; b3
	const BITTER_BERRY ; b4
	const MINT_BERRY   ; b5
	const MIRACLEBERRY ; b6
	const MYSTERYBERRY ; b7
	const BERRY        ; b8
	const GOLD_BERRY   ; b9
	const RED_APRICORN ; ba
	const BLU_APRICORN ; bb
	const YLW_APRICORN ; bc
	const GRN_APRICORN ; bd
	const WHT_APRICORN ; be
	const BLK_APRICORN ; bf
	const PNK_APRICORN ; c0
	const NORMAL_BOX   ; c1
	const GORGEOUS_BOX ; c2
	const ITEM_C3      ; c3
	const ITEM_C4      ; c4
	const ITEM_C5      ; c5
	const ITEM_C6      ; c6
	const ITEM_C7      ; c7
	const ITEM_C8      ; c8
	const ITEM_C9      ; c9
	const ITEM_CA      ; ca
	const ITEM_CB      ; cb
	const ITEM_CC      ; cc
	const ITEM_CD      ; cd
	const ITEM_CE      ; ce
	const ITEM_CF      ; cf
	const ITEM_D0      ; d0
	const ITEM_D1      ; d1
	const ITEM_D2      ; d2
	const ITEM_D3      ; d3
	const ITEM_D4      ; d4
	const ITEM_D5      ; d5
	const ITEM_D6      ; d6
	const ITEM_D7      ; d7
	const ITEM_D8      ; d8
	const ITEM_D9      ; d9
	const ITEM_DA      ; da
	const ITEM_DB      ; db
	const ITEM_DC      ; dc
	const ITEM_DD      ; dd
	const ITEM_DE      ; de
	const ITEM_DF      ; df
	const ITEM_E0      ; e0
	const ITEM_E1      ; e1
	const ITEM_E2      ; e2
	const ITEM_E3      ; e3
	const ITEM_E4      ; e4
	const ITEM_E5      ; e5
	const ITEM_E6      ; e6
	const ITEM_E7      ; e7
	const ITEM_E8      ; e8
	const ITEM_E9      ; e9
	const ITEM_EA      ; ea
	const ITEM_EB      ; eb
	const ITEM_EC      ; ec
	const ITEM_ED      ; ed
	const ITEM_EE      ; ee
	const ITEM_EF      ; ef
	const ITEM_F0      ; f0
	const ITEM_F1      ; f1
	const ITEM_F2      ; f2
	const ITEM_F3      ; f3
	const ITEM_F4      ; f4
	const ITEM_F5      ; f5
	const ITEM_F6      ; f6
	const ITEM_F7      ; f7
	const ITEM_F8      ; f8
	const ITEM_F9      ; f9
	const ITEM_FA      ; fa
	const ITEM_FB      ; fb
	const ITEM_FC      ; fc
	const ITEM_FD      ; fd
	const ITEM_FE      ; fe

USE_SCRIPT_VAR EQU $00
ITEM_FROM_MEM  EQU $ff

; leftovers from red
SAFARI_BALL    EQU $08 ; MOON_STONE
MOON_STONE_RED EQU $0a ; BURN_HEAL
FULL_HEAL_RED  EQU $34 ; X_SPEED
