; MoveEffectsPointers indexes (see data/moves/effects_pointers.asm)
	const_def
	const EFFECT_NORMAL_HIT         ; 01
	const EFFECT_SLEEP              ; 02
	const EFFECT_POISON_HIT         ; 03
	const EFFECT_LEECH_HIT          ; 04
	const EFFECT_BURN_HIT           ; 05
	const EFFECT_FREEZE_HIT         ; 06
	const EFFECT_PARALYZE_HIT       ; 07
	const EFFECT_SELFDESTRUCT       ; 08
	const EFFECT_DREAM_EATER        ; 09
	const EFFECT_MIRROR_MOVE        ; 0a
	const EFFECT_ATTACK_UP          ; 0b
	const EFFECT_DEFENSE_UP         ; 0c
	const EFFECT_SPEED_UP           ; 0d
	const EFFECT_SP_ATK_UP          ; 0e
	const EFFECT_SP_DEF_UP          ; 0f
	const EFFECT_ACCURACY_UP        ; 10
	const EFFECT_EVASION_UP         ; 11
	const EFFECT_ALWAYS_HIT         ; 12
	const EFFECT_ATTACK_DOWN        ; 13
	const EFFECT_DEFENSE_DOWN       ; 14
	const EFFECT_SPEED_DOWN         ; 15
	const EFFECT_SP_ATK_DOWN        ; 16
	const EFFECT_SP_DEF_DOWN        ; 17
	const EFFECT_ACCURACY_DOWN      ; 18
	const EFFECT_EVASION_DOWN       ; 19
	const EFFECT_RESET_STATS        ; 1a
	const EFFECT_BIDE               ; 1b
	const EFFECT_RAMPAGE            ; 1c
	const EFFECT_FORCE_SWITCH       ; 1d
	const EFFECT_MULTI_HIT          ; 1e
	const EFFECT_CONVERSION         ; 1f
	const EFFECT_FLINCH_HIT         ; 20
	const EFFECT_HEAL               ; 21
	const EFFECT_TOXIC              ; 22
	const EFFECT_PAY_DAY            ; 23
	const EFFECT_TRI_ATTACK         ; 24
	const EFFECT_CONDITIONAL_BOOST  ; 25
	const EFFECT_OHKO               ; 26
	const EFFECT_RAZOR_WIND         ; 27
	const EFFECT_SUPER_FANG         ; 28
	const EFFECT_STATIC_DAMAGE      ; 29
	const EFFECT_TRAP_TARGET        ; 2a
	const EFFECT_BODY_SLAM          ; 2b
	const EFFECT_DOUBLE_HIT         ; 2c
	const EFFECT_JUMP_KICK          ; 2d
	const EFFECT_STATUS_SELF        ; 2e
	const EFFECT_RECOIL_HIT_QUARTER ; 2f
	const EFFECT_CONFUSE            ; 30
	const EFFECT_ATTACK_UP_2        ; 31
	const EFFECT_DEFENSE_UP_2       ; 32
	const EFFECT_SPEED_UP_2         ; 33
	const EFFECT_SP_ATK_UP_2        ; 34
	const EFFECT_SP_DEF_UP_2        ; 35
	const EFFECT_ACCURACY_UP_2      ; 36
	const EFFECT_EVASION_UP_2       ; 37
	const EFFECT_TRANSFORM          ; 38
	const EFFECT_ATTACK_DOWN_2      ; 39
	const EFFECT_DEFENSE_DOWN_2     ; 3a
	const EFFECT_SPEED_DOWN_2       ; 3b
	const EFFECT_SP_ATK_DOWN_2      ; 3c
	const EFFECT_SP_DEF_DOWN_2      ; 3d
	const EFFECT_ACCURACY_DOWN_2    ; 3e
	const EFFECT_EVASION_DOWN_2     ; 3f
	const EFFECT_POISON             ; 40
	const EFFECT_PARALYZE           ; 41
	const EFFECT_ATTACK_DOWN_HIT    ; 42
	const EFFECT_DEFENSE_DOWN_HIT   ; 43
	const EFFECT_SPEED_DOWN_HIT     ; 44
	const EFFECT_SP_ATK_DOWN_HIT    ; 45
	const EFFECT_SP_DEF_DOWN_HIT    ; 46
	const EFFECT_ACCURACY_DOWN_HIT  ; 47
	const EFFECT_EVASION_DOWN_HIT   ; 48
	const EFFECT_SKY_ATTACK         ; 49
	const EFFECT_CONFUSE_HIT        ; 4a
	const EFFECT_POISON_MULTI_HIT   ; 4b
	const EFFECT_LOW_KICK           ; 4c
	const EFFECT_HYPER_BEAM         ; 4d
	const EFFECT_RAGE               ; 4e
	const EFFECT_MIMIC              ; 4f
	const EFFECT_METRONOME          ; 50
	const EFFECT_STATUS_OPP         ; 51
	const EFFECT_SPLASH             ; 52
	const EFFECT_DISABLE            ; 53
	const EFFECT_LEVEL_DAMAGE       ; 54
	const EFFECT_PSYWAVE            ; 55
	const EFFECT_COUNTER            ; 56
	const EFFECT_ENCORE             ; 57
	const EFFECT_PAIN_SPLIT         ; 58
	const EFFECT_SNORE              ; 59
	const EFFECT_CONVERSION2        ; 5a
	const EFFECT_LOCK_ON            ; 5b
	const EFFECT_SKETCH             ; 5c
	const EFFECT_STRUGGLE           ; 5d
	const EFFECT_SLEEP_TALK         ; 5e
	const EFFECT_REVERSAL           ; 5f
	const EFFECT_FALSE_SWIPE        ; 60
	const EFFECT_PRIORITY_HIT       ; 61
	const EFFECT_TRIPLE_KICK        ; 62
	const EFFECT_THIEF              ; 63
	const EFFECT_FLAME_WHEEL        ; 64
	const EFFECT_GROWTH             ; 65
	const EFFECT_PROTECT            ; 66
	const EFFECT_FORESIGHT          ; 67
	const EFFECT_ENDURE             ; 68
	const EFFECT_ROLLOUT            ; 69
	const EFFECT_SWAGGER            ; 6a
	const EFFECT_FURY_CUTTER        ; 6b
	const EFFECT_RETURN             ; 6c
	const EFFECT_PRESENT            ; 6d
	const EFFECT_FRUSTRATION        ; 6e
	const EFFECT_SACRED_FIRE        ; 6f
	const EFFECT_MAGNITUDE          ; 70
	const EFFECT_BATON_PASS         ; 71
	const EFFECT_PURSUIT            ; 72
	const EFFECT_RAPID_SPIN         ; 73
	const EFFECT_BUG_BITE           ; 74
	const EFFECT_SUNLIGHT_HEAL      ; 75
	const EFFECT_EXTREMESPEED       ; 76
	const EFFECT_VARIABLE_TYPE      ; 77
	const EFFECT_DEFENSE_UP_HIT     ; 78
	const EFFECT_ATTACK_UP_HIT      ; 79
	const EFFECT_ALL_UP_HIT         ; 7a
	const EFFECT_FAKE_OUT           ; 7b
	const EFFECT_MIRROR_COAT        ; 7c
	const EFFECT_SKULL_BASH         ; 7d
	const EFFECT_COND_BOOST_FLINCH  ; 7e
	const EFFECT_EARTHQUAKE         ; 7f
	const EFFECT_FUTURE_SIGHT       ; 80
	const EFFECT_SOLARBEAM          ; 81
	const EFFECT_THUNDER            ; 82
	const EFFECT_TELEPORT           ; 83
	const EFFECT_BEAT_UP            ; 84
	const EFFECT_FLY                ; 85
	const EFFECT_DEFENSE_CURL       ; 86
	const EFFECT_ELEMENTAL_FANG     ; 87
	const EFFECT_FLARE_BLITZ        ; 88
	const EFFECT_SUCKER_PUNCH       ; 89
	const EFFECT_PLAY_NICE          ; 8a
	const EFFECT_VENOM_DRENCH       ; 8b
	const EFFECT_ATK_DEF_DOWN       ; 8c
	const EFFECT_ATK_DOWN_PRIORITY  ; 8d
	const EFFECT_POISON_SPEED_DOWN  ; 8e
	const EFFECT_TEARFUL_LOOK       ; 8f
	const EFFECT_CAPTIVATE          ; 90
	const EFFECT_ATK_SP_ATK_DOWN    ; 91
	const EFFECT_CONFIDE            ; 92
	const EFFECT_EERIE_SPELL ; const EFFECT_TAR_SHOT           ; 93
	const EFFECT_BLIZZARD           ; 94
	const EFFECT_METAL_BURST        ; 95
	const EFFECT_FLATTER            ; 96
	const EFFECT_SUPERPOWER         ; 97
	const EFFECT_SHEER_COLD         ; 98
	const EFFECT_TOXIC_HIT          ; 99
	const EFFECT_COSMIC_POWER       ; 9a
	const EFFECT_HONE_CLAWS         ; 9b
	const EFFECT_CALM_MIND          ; 9c
	const EFFECT_BULK_UP            ; 9d
	const EFFECT_WORK_UP            ; 9e
	const EFFECT_ACUPRESSURE        ; 9f
	const EFFECT_BARB_BARRAGE ; const EFFECT_GEOMANCY           ; a0
	; const EFFECT_SHIFT_GEAR         ; a1
	const EFFECT_DEFENSE_UP_3       ; a2
	const EFFECT_SP_ATK_UP_3        ; a3
	const EFFECT_CLOSE_COMBAT       ; a4
	const EFFECT_BURN_UP            ; a5
	const EFFECT_KNOCK_OFF          ; a6
	const EFFECT_WATER_SPOUT        ; a7
	const EFFECT_WRING_OUT          ; a8
	const EFFECT_PSYSHOCK           ; a9
	const EFFECT_FOUL_PLAY          ; aa
	const EFFECT_DRACO_METEOR       ; ab
	const EFFECT_CURE_SLEEP_HIT     ; ac
	const EFFECT_HAMMER_ARM         ; ad
	const EFFECT_RESET_STATS_HIT    ; ae
	const EFFECT_DEFOG              ; af
	const EFFECT_DRAGON_DANCE       ; b0
	const EFFECT_FREEZE_DRY         ; b1
	const EFFECT_ALWAYS_CRIT        ; b2
	const EFFECT_HURRICANE          ; b3
	const EFFECT_PSYCHO_SHIFT       ; b4
	const EFFECT_ROOST              ; b5
	const EFFECT_BRICK_BREAK        ; b6
	const EFFECT_VITAL_THROW        ; b7
	const EFFECT_FORCE_SWITCH_HIT   ; b8
	const EFFECT_TRAP_HIT           ; b9
	const EFFECT_NAIL_DOWN          ; ba
	const EFFECT_DYNAMO_RUSH        ; bb
	const EFFECT_SPEED_UP_HIT       ; bc
	const EFFECT_SACRED_SWORD       ; bd
	const EFFECT_UPROOT             ; be
	const EFFECT_UPROAR             ; bf
	const EFFECT_FELL_STINGER       ; c0
	const EFFECT_BOUNCE             ; c1
	const EFFECT_FEINT              ; c2
	const EFFECT_WEATHER_BALL       ; c3
	const EFFECT_CURE_PARALYSIS_HIT ; c4
	const EFFECT_SP_DEF_DOWN_2_HIT  ; c5
	const EFFECT_BELCH              ; c6
	const EFFECT_YAWN               ; c7
	const EFFECT_DIG                ; c8
	const EFFECT_DIVE               ; c9
	const EFFECT_SHADOW_FORCE       ; ca
	const EFFECT_WHIRLPOOL          ; cb
	const EFFECT_SPIKY_SHIELD       ; cc
	const EFFECT_TRIPLE_HIT ; const EFFECT_KINGS_SHIELD       ; cd
	const EFFECT_STONE_AXE ; const EFFECT_BANEFUL_BUNKER     ; ce
	const EFFECT_OBSTRUCT           ; cf
	const EFFECT_CRAFTY_SHIELD      ; d0
	const EFFECT_FIRST_IMPRESSION   ; d1
	const EFFECT_BURN               ; d2
	const EFFECT_SP_ATK_UP_HIT      ; d3
	const EFFECT_TRICK_ROOM         ; d4
	const EFFECT_FINAL_GAMBIT       ; d5
	const EFFECT_BODY_PRESS         ; d6
	const EFFECT_MEMENTO            ; d7
	const EFFECT_HEALING_WISH       ; d8
	const EFFECT_HEAVY_SLAM         ; d9
	const EFFECT_ENDEAVOR           ; da
	const EFFECT_STRENGTH_SAP       ; db
	const EFFECT_SPIT_UP            ; dc
	const EFFECT_MISTY_AMBUSH       ; dd
	const EFFECT_DROWSY_WRATH       ; de
	const EFFECT_PRIORITY_MULTI_HIT ; df
	const EFFECT_POWDER             ; e0
	const EFFECT_STATUS_OPP_ACC     ; e1 (same as EFFECT_STATUS_OPP, but bypasses accuracy checks)
	const EFFECT_DEFENSE_UP_2_HIT   ; e2
	const EFFECT_FOCUS_PUNCH        ; e3
	; const EFFECT_BEAK_BLAST         ; e4
	const EFFECT_SHELL_TRAP         ; e5
	const EFFECT_REVENGE            ; e6
	const EFFECT_SHORE_UP           ; e7
	; const EFFECT_CLANGING_SCALES    ; e8
	const EFFECT_RECOIL_HIT_HALF    ; e9
	const EFFECT_RECOIL_HIT_THIRD   ; ea
	const EFFECT_MIND_BLOWN         ; eb
	const EFFECT_PUNISHMENT         ; ec
	const EFFECT_STORED_POWER       ; ed
	; const EFFECT_TRICK_ROOM_HIT     ; ee
	const EFFECT_VOLT_TACKLE        ; ef
	const EFFECT_METEOR_BEAM        ; f1
	const EFFECT_POLTERGEIST        ; f2
	const EFFECT_SCALE_SHOT         ; f3
	const EFFECT_MISTY_EXPLOSION    ; f4
	const EFFECT_TRUMP_CARD         ; f5
	const EFFECT_U_TURN             ; f6
	const EFFECT_PARTING_SHOT       ; f7
	const EFFECT_ELECTRO_BALL       ; f8
	const EFFECT_GYRO_BALL          ; f9
	const EFFECT_SYNCHRONOISE       ; fa
	const EFFECT_INCINERATE         ; fb
	const EFFECT_GUILE_FANG         ; fc
	const EFFECT_DATA_PULSE         ; fd
	const EFFECT_ME_FIRST           ; fe
NUM_MOVE_EFECTS EQU const_value
