command: MACRO
	enum \1_command
\1 EQUS "db \1_command"
ENDM

; BattleCommandPointers indexes (see data/battle/effect_command_pointers.asm)
	enum_start 1
	command checkturn               ; 01
	command checkobedience          ; 02
	command usedmovetext            ; 03
	command doturn                  ; 04
	command critical                ; 05
	command damagestats             ; 06
	command stab                    ; 07
	command damagevariation         ; 08
	command checkhit                ; 09
	command lowersub                ; 0a
	command moveanimnosub           ; 0b
	command raisesub                ; 0c
	command failuretext             ; 0d
	command applydamage             ; 0e
	command criticaltext            ; 0f
	command supereffectivetext      ; 10
	command checkfaint              ; 11
	command buildopponentrage       ; 12
	command poisontarget            ; 13
	command sleeptarget             ; 14
	command draintarget             ; 15
	command eatdream                ; 16
	command burntarget              ; 17
	command freezetarget            ; 18
	command paralyzetarget          ; 19
	command selfdestruct            ; 1a
	command mirrormove              ; 1b
	command statup                  ; 1c
	command statdown                ; 1d
	command payday                  ; 1e
	command conversion              ; 1f
	command resetstats              ; 20
	command storeenergy             ; 21
	command unleashenergy           ; 22
	command forceswitch             ; 23
	command endloop                 ; 24
	command flinchtarget            ; 25
	command ohko                    ; 26
	command recoil                  ; 27
	command mist                    ; 28
	command statustargetself        ; 29
	command confuse                 ; 2a
	command confusetarget           ; 2b
	command heal                    ; 2c
	command transform               ; 2d
	command screen                  ; 2e
	command poison                  ; 2f
	command paralyze                ; 30
	command substitute              ; 31
	command rechargenextturn        ; 32
	command mimic                   ; 33
	command metronome               ; 34
	command leechseed               ; 35
	command splash                  ; 36
	command disable                 ; 37
	command cleartext               ; 38
	command charge                  ; 39
	command checkcharge             ; 3a
	command traptarget              ; 3b
	command rampage                 ; 3c
	command checkrampage            ; 3d
	command constantdamage          ; 3e
	command counter                 ; 3f
	command encore                  ; 40
	command painsplit               ; 41
	command snore                   ; 42
	command conversion2             ; 43
	command lockon                  ; 44
	command sketch                  ; 45
	command defrostopponent         ; 46
	command sleeptalk               ; 47
	command destinybond             ; 48
	command spite                   ; 49
	command falseswipe              ; 4a
	command kingsrock               ; 4b
	command triplekick              ; 4c
	command kickcounter             ; 4d
	command thief                   ; 4e
	command nightmare               ; 4f
	command defrost                 ; 50
	command curse                   ; 51
	command protect                 ; 52
	command foresight               ; 53
	command perishsong              ; 54
	command endure                  ; 55
	command checkcurl               ; 56
	command rolloutpower            ; 57
	command lowkick                 ; 58
	command furycutter              ; 59
	command attract                 ; 5a
	command happinesspower          ; 5b
	command present                 ; 5c
	command damagecalc              ; 5d
	command frustrationpower        ; 5e
	command checksafeguard          ; 5f
	command getmagnitude            ; 60
	command batonpass               ; 61
	command pursuit                 ; 62
	command clearhazards            ; 63
	command hiddenpower             ; 64
	command attackup                ; 65
	command defenseup               ; 66
	command speedup                 ; 67
	command specialattackup         ; 68
	command specialdefenseup        ; 69
	command accuracyup              ; 6a
	command evasionup               ; 6b
	command attackup2               ; 6c
	command defenseup2              ; 6d
	command speedup2                ; 6e
	command specialattackup2        ; 6f
	command specialdefenseup2       ; 70
	command accuracyup2             ; 71
	command evasionup2              ; 72
	command attackdown              ; 73
	command defensedown             ; 74
	command speeddown               ; 75
	command specialattackdown       ; 76
	command specialdefensedown      ; 77
	command accuracydown            ; 78
	command evasiondown             ; 79
	command attackdown2             ; 7a
	command defensedown2            ; 7b
	command speeddown2              ; 7c
	command specialattackdown2      ; 7d
	command specialdefensedown2     ; 7e
	command accuracydown2           ; 7f
	command evasiondown2            ; 80
	command statupmessage           ; 81
	command statdownmessage         ; 82
	command statupfailtext          ; 83
	command statdownfailtext        ; 84
	command effectchance            ; 85
	command statdownanim            ; 86
	command statupanim              ; 87
	command switchturn              ; 88
	command bellydrum               ; 89
	command psychup                 ; 8a
	command rage                    ; 8b
	command checkfuturesight        ; 8c
	command futuresight             ; 8d
	command skipsuncharge           ; 8e
	command thunderaccuracy         ; 8f
	command teleport                ; 90
	command beatup                  ; 91
	command ragedamage              ; 92
	command resettypematchup        ; 93
	command allstatsup              ; 94
	command bidefailtext            ; 95
	command raisesubnoanim          ; 96
	command lowersubnoanim          ; 97
	command beatupfailtext          ; 98
	command clearmissdamage         ; 99
	command movedelay               ; 9a
	command moveanim                ; 9b
	command tristatuschance         ; 9c
	command supereffectivelooptext  ; 9d
	command startloop               ; 9e
	command curl                    ; 9f
	command growth                  ; a0
	command firefang                ; a1
	command icefang                 ; a2
	command thunderfang             ; a3
	command bugbite                 ; a4
	command conditionalboost        ; a5
	command suckerpunch             ; a6
	command blizzardaccuracy        ; a7
	command superpower              ; a8
	command cosmicpower             ; a9
	command honeclaws               ; aa
	command closecombat             ; ab
	command burnup                  ; ac
	command calmmind                ; ad
	command knockoff                ; ae
	command bulkup                  ; af
	command overheat                ; b0
	command multistatdown           ; b1
	command multistatdownmessage    ; b2
	command docurestatus            ; b3
	command trick                   ; b4
	command hammerarm               ; b5
	command resetstatstarget        ; b6
	command defog                   ; b7
	command dragondance             ; b8
	command workup                  ; b9
	command psychoshift             ; ba
	command roost                   ; bb
	command brickbreak              ; bc
	command traphit                 ; bd
	command dynamorush              ; be
	command brightmoss              ; bf
	command uproot                  ; c0
	command uproar                  ; c1
	command uproarstate             ; c2
	command soak                    ; c3
	command weatherball             ; c4
	command captivate               ; c5
	command yawn                    ; c6
	command craftyshield            ; c7

	enum_start $fe
	command endturn                 ; fe
	command endmove                 ; ff
