command: MACRO
	enum \1_command
\1 EQUS "db \1_command"
ENDM

; BattleCommandPointers indexes (see data/battle/effect_command_pointers.asm)
	enum_start 1
	command checkturn               ; 01
	command checkobedience          ; 02
	command usedmovetext            ; 03
	command doturn                  ; 04
	command critical                ; 05
	command damagestats             ; 06
	command stab                    ; 07
	command damagevariation         ; 08
	command checkhit                ; 09
	command lowersub                ; 0a
	command moveanimnosub           ; 0b
	command raisesub                ; 0c
	command failuretext             ; 0d
	command applydamage             ; 0e
	command criticaltext            ; 0f
	command supereffectivetext      ; 10
	command checkfaint              ; 11
	command buildopponentrage       ; 12
	command poisontarget            ; 13
	command sleeptarget             ; 14
	command draintarget             ; 15
	command eatdream                ; 16
	command burntarget              ; 17
	command freezetarget            ; 18
	command paralyzetarget          ; 19
	command selfdestruct            ; 1a
	command mirrormove              ; 1b
	command statup                  ; 1c
	command statdown                ; 1d
	command payday                  ; 1e
	command resetstats              ; 1f
	command storeenergy             ; 20
	command unleashenergy           ; 21
	command forceswitch             ; 22
	command endloop                 ; 23
	command flinchtarget            ; 24
	command ohko                    ; 25
	command recoil                  ; 26
	                                ; 27
	command statustargetself        ; 28
	command confuse                 ; 29
	command confusetarget           ; 2a
	command heal                    ; 2b
	command transform               ; 2c
	                                ; 2d
	command poison                  ; 2e
	command paralyze                ; 2f
	                                ; 30
	command rechargenextturn        ; 31
	command mimic                   ; 32
	command metronome               ; 33
	command leechseed               ; 34
	command splash                  ; 35
	command disable                 ; 36
	command cleartext               ; 37
	command charge                  ; 38
	command checkcharge             ; 39
	command traptarget              ; 3a
	command rampage                 ; 3b
	command checkrampage            ; 3c
	command constantdamage          ; 3d
	command counter                 ; 3e
	command encore                  ; 3f
	command painsplit               ; 40
	command snore                   ; 41
	command conversion2             ; 42
	command lockon                  ; 43
	command sketch                  ; 44
	command defrostopponent         ; 45
	command sleeptalk               ; 46
	                                ; 47
	command spite                   ; 48
	command falseswipe              ; 49
	command kingsrock               ; 4a
	command triplekick              ; 4b
	command kickcounter             ; 4c
	command thief                   ; 4d
	command nightmare               ; 4e
	command defrost                 ; 4f
	                                ; 50
	command protect                 ; 51
	command foresight               ; 52
	                                ; 53
	command endure                  ; 54
	command checkcurl               ; 55
	command rolloutpower            ; 56
	command lowkick                 ; 57
	command furycutter              ; 58
	command attract                 ; 59
	command happinesspower          ; 5a
	command present                 ; 5b
	command damagecalc              ; 5c
	command frustrationpower        ; 5d
	command checksafeguard          ; 5e
	command getmagnitude            ; 5f
	command batonpass               ; 60
	command pursuit                 ; 61
	command clearhazards            ; 62
	command hiddenpower             ; 63
	command attackup                ; 64
	command defenseup               ; 65
	command speedup                 ; 66
	command specialattackup         ; 67
	command specialdefenseup        ; 68
	command accuracyup              ; 69
	command evasionup               ; 6a
	command attackup2               ; 6b
	command defenseup2              ; 6c
	command speedup2                ; 6d
	command specialattackup2        ; 6e
	command specialdefenseup2       ; 6f
	command accuracyup2             ; 70
	command evasionup2              ; 71
	command attackdown              ; 72
	command defensedown             ; 73
	command speeddown               ; 74
	command specialattackdown       ; 75
	command specialdefensedown      ; 76
	command accuracydown            ; 77
	command evasiondown             ; 78
	command attackdown2             ; 79
	command defensedown2            ; 7a
	command speeddown2              ; 7b
	command specialattackdown2      ; 7c
	command specialdefensedown2     ; 7d
	command accuracydown2           ; 7e
	command evasiondown2            ; 7f
	command statupmessage           ; 80
	command statdownmessage         ; 81
	command statupfailtext          ; 82
	command statdownfailtext        ; 83
	command effectchance            ; 84
	command statdownanim            ; 85
	command statupanim              ; 86
	command switchturn              ; 87
	                                ; 88
	                                ; 89
	command rage                    ; 8a
	command checkfuturesight        ; 8b
	command futuresight             ; 8c
	command skipsuncharge           ; 8d
	command thunderaccuracy         ; 8e
	command teleport                ; 8f
	command beatup                  ; 90
	command ragedamage              ; 91
	command resettypematchup        ; 92
	command allstatsup              ; 93
	command bidefailtext            ; 94
	command raisesubnoanim          ; 95
	command lowersubnoanim          ; 96
	command beatupfailtext          ; 97
	command clearmissdamage         ; 98
	command movedelay               ; 99
	command moveanim                ; 9a
	command tristatuschance         ; 9b
	command supereffectivelooptext  ; 9c
	command startloop               ; 9d
	command curl                    ; 9e
	command growth                  ; 9f
	command elementalfang           ; a0
	command bugbite                 ; a1
	command conditionalboost        ; a2
	command suckerpunch             ; a3
	command blizzardaccuracy        ; a4
	command superpower              ; a5
	command cosmicpower             ; a6
	command honeclaws               ; a7
	command closecombat             ; a8
	command burnup                  ; a9
	command calmmind                ; aa
	command knockoff                ; ab
	command bulkup                  ; ac
	command overheat                ; ad
	command multistatdown           ; ae
	command multistatdownmessage    ; af
	command docurestatus            ; b0
	command trick                   ; b1
	command hammerarm               ; b2
	command resetstatstarget        ; b3
	command defog                   ; b4
	command dragondance             ; b5
	command workup                  ; b6
	command psychoshift             ; b7
	command roost                   ; b8
	command brickbreak              ; b9
	command traphit                 ; ba
	command dynamorush              ; bb
	command brightmoss              ; bc
	command uproot                  ; bd
	command uproar                  ; be
	command uproarstate             ; bf
	command soak                    ; c0
	command weatherball             ; c1
	command captivate               ; c2
	command yawn                    ; c3
	command craftyshield            ; c4
	command burn                    ; c5

	enum_start $fe
	command endturn                 ; fe
	command endmove                 ; ff
