command: MACRO
	enum \1_command
\1 EQUS "db \1_command"
ENDM

; BattleCommandPointers indexes (see data/battle/effect_command_pointers.asm)
	enum_start 1
	command checkturn               ; 01
	command checkobedience          ; 02
	command usedmovetext            ; 03
	command doturn                  ; 04
	command critical                ; 05
	command damagestats             ; 06
	command stab                    ; 07
	command damagevariation         ; 08
	command checkhit                ; 09
	command lowersub                ; 0a
	command moveanimnosub           ; 0b
	command raisesub                ; 0c
	command failuretext             ; 0d
	command applydamage             ; 0e
	command criticaltext            ; 0f
	command supereffectivetext      ; 10
	command checkfaint              ; 11
	command buildopponentrage       ; 12
	command poisontarget            ; 13
	command sleeptarget             ; 14
	command draintarget             ; 15
	command eatdream                ; 16
	command burntarget              ; 17
	command freezetarget            ; 18
	command paralyzetarget          ; 19
	command selfdestruct            ; 1a
	command mirrormove              ; 1b
	command statup                  ; 1c
	command statdown                ; 1d
	command payday                  ; 1e
	command conversion              ; 1f
	command resetstats              ; 20
	command storeenergy             ; 21
	command unleashenergy           ; 22
	command forceswitch             ; 23
	command endloop                 ; 24
	command flinchtarget            ; 25
	command ohko                    ; 26
	command recoil                  ; 27
	command mist                    ; 28
	command focusenergy             ; 29
	command confuse                 ; 2a
	command confusetarget           ; 2b
	command heal                    ; 2c
	command transform               ; 2d
	command screen                  ; 2e
	command poison                  ; 2f
	command paralyze                ; 30
	command substitute              ; 31
	command rechargenextturn        ; 32
	command mimic                   ; 33
	command metronome               ; 34
	command leechseed               ; 35
	command splash                  ; 36
	command disable                 ; 37
	command cleartext               ; 38
	command charge                  ; 39
	command checkcharge             ; 3a
	command traptarget              ; 3b
	command rampage                 ; 3c
	command checkrampage            ; 3d
	command constantdamage          ; 3e
	command counter                 ; 3f
	command encore                  ; 40
	command painsplit               ; 41
	command snore                   ; 42
	command conversion2             ; 43
	command lockon                  ; 44
	command sketch                  ; 45
	command defrostopponent         ; 46
	command sleeptalk               ; 47
	command destinybond             ; 48
	command spite                   ; 49
	command falseswipe              ; 4a
	command healbell                ; 4b
	command kingsrock               ; 4c
	command triplekick              ; 4d
	command kickcounter             ; 4e
	command thief                   ; 4f
	command arenatrap               ; 50
	command nightmare               ; 51
	command defrost                 ; 52
	command curse                   ; 53
	command protect                 ; 54
	command spikes                  ; 55
	command foresight               ; 56
	command perishsong              ; 57
	command startsandstorm          ; 58
	command endure                  ; 59
	command checkcurl               ; 5a
	command rolloutpower            ; 5b
	command lowkick                 ; 5c
	command furycutter              ; 5d
	command attract                 ; 5e
	command happinesspower          ; 5f
	command present                 ; 60
	command damagecalc              ; 61
	command frustrationpower        ; 62
	command safeguard               ; 63
	command checksafeguard          ; 64
	command getmagnitude            ; 65
	command batonpass               ; 66
	command pursuit                 ; 67
	command clearhazards            ; 68
	command healsun                 ; 69
	command hiddenpower             ; 6a
	command startrain               ; 6b
	command startsun                ; 6c
	command attackup                ; 6d
	command defenseup               ; 6e
	command speedup                 ; 6f
	command specialattackup         ; 70
	command specialdefenseup        ; 71
	command accuracyup              ; 72
	command evasionup               ; 73
	command attackup2               ; 74
	command defenseup2              ; 75
	command speedup2                ; 76
	command specialattackup2        ; 77
	command specialdefenseup2       ; 78
	command accuracyup2             ; 79
	command evasionup2              ; 7a
	command attackdown              ; 7b
	command defensedown             ; 7c
	command speeddown               ; 7d
	command specialattackdown       ; 7e
	command specialdefensedown      ; 7f
	command accuracydown            ; 80
	command evasiondown             ; 81
	command attackdown2             ; 82
	command defensedown2            ; 83
	command speeddown2              ; 84
	command specialattackdown2      ; 85
	command specialdefensedown2     ; 86
	command accuracydown2           ; 87
	command evasiondown2            ; 88
	command statupmessage           ; 89
	command statdownmessage         ; 8a
	command statupfailtext          ; 8b
	command statdownfailtext        ; 8c
	command effectchance            ; 8d
	command statdownanim            ; 8e
	command statupanim              ; 8f
	command switchturn              ; 90
	; command fakeout                 ; 91
	command bellydrum               ; 92
	command psychup                 ; 93
	command rage                    ; 94
	command checkfuturesight        ; 95
	command futuresight             ; 96
	command skipsuncharge           ; 97
	command thunderaccuracy         ; 98
	command teleport                ; 99
	command beatup                  ; 9a
	command ragedamage              ; 9b
	command resettypematchup        ; 9c
	command allstatsup              ; 9d
	command bidefailtext            ; 9e
	command raisesubnoanim          ; 9f
	command lowersubnoanim          ; a0
	command beatupfailtext          ; a1
	command clearmissdamage         ; a2
	command movedelay               ; a3
	command moveanim                ; a4
	command tristatuschance         ; a5
	command supereffectivelooptext  ; a6
	command startloop               ; a7
	command curl                    ; a8
	command growth                  ; a9
	command firefang                ; aa
	command icefang                 ; ab
	command thunderfang             ; ac
	command shellsmash              ; ad
	command bugbite                 ; ae
	command quiverdance             ; af
	command conditionalboost        ; b0
	command suckerpunch             ; b1
	command starthail               ; b2
	command blizzardaccuracy        ; b3
	command superpower              ; b4
	command cosmicpower             ; b5
	command honeclaws               ; b6
	command closecombat             ; b7
	command burnup                  ; b8
	command calmmind                ; b9
	command knockoff                ; ba
	command bulkup                  ; bb
	command overheat                ; bc
	command reflecttype             ; bd
	command venomdrench             ; be
	command venomdrenchmessage      ; bf
	command docurestatus            ; c0
	command trick                   ; c1
	command hammerarm               ; c2
	command resetstatstarget        ; c3
	command startfog                ; c4
	command defog                   ; c5

	enum_start $fe
	command endturn                 ; fe
	command endmove                 ; ff
