SECTION "Mon Icons 1", ROMX

; Icons: ; used only for BANK(Icons)

NullIcon:
; PoliwagIcon:      INCBIN "gfx/icons/poliwag.2bpp"
DiglettIcon:      INCBIN "gfx/icons/diglett.2bpp"
; BugIcon:          INCBIN "gfx/icons/bug.2bpp"
; EquineIcon:       INCBIN "gfx/icons/equine.2bpp"
; BlobIcon:         INCBIN "gfx/icons/blob.2bpp"
; VoltorbIcon:      INCBIN "gfx/icons/voltorb.2bpp"
; MothIcon:         INCBIN "gfx/icons/moth.2bpp"
; BatIcon:          INCBIN "gfx/icons/bat.2bpp"
EggIcon:          INCBIN "gfx/icons/egg.2bpp"
BulbasaurIcon:    INCBIN "gfx/icons/bulbasaur.2bpp"
CharmanderIcon:   INCBIN "gfx/icons/charmander.2bpp"
CharizardIcon:    INCBIN "gfx/icons/charizard.2bpp"
SquirtleIcon:     INCBIN "gfx/icons/squirtle.2bpp"
CaterpillarIcon:  INCBIN "gfx/icons/caterpillar.2bpp"
KakunaIcon:       INCBIN "gfx/icons/kakuna.2bpp"
VivillonIcon:     INCBIN "gfx/icons/vivillon.2bpp"
BeedrillIcon:     INCBIN "gfx/icons/beedrill.2bpp"
RattataIcon:      INCBIN "gfx/icons/rattata.2bpp"
PikachuIcon:      INCBIN "gfx/icons/pikachu.2bpp"
MonsterIcon:      INCBIN "gfx/icons/monster.2bpp"
NidoranFIcon:     INCBIN "gfx/icons/nidoran_f.2bpp"
ClefairyIcon:     INCBIN "gfx/icons/clefairy.2bpp"
FoxIcon:          INCBIN "gfx/icons/fox.2bpp"
JigglypuffIcon:   INCBIN "gfx/icons/jigglypuff.2bpp"
ZubatIcon:        INCBIN "gfx/icons/zubat.2bpp"
OddishIcon:       INCBIN "gfx/icons/oddish.2bpp"
GrubbinIcon:      INCBIN "gfx/icons/grubbin.2bpp"
MeowthIcon:       INCBIN "gfx/icons/meowth.2bpp"
PsyduckIcon:      INCBIN "gfx/icons/psyduck.2bpp"
AbraIcon:         INCBIN "gfx/icons/abra.2bpp"
AlakazamIcon:     INCBIN "gfx/icons/alakazam.2bpp"
FighterIcon:      INCBIN "gfx/icons/fighter.2bpp"
VictreebelIcon:   INCBIN "gfx/icons/victreebel.2bpp"
JellyfishIcon:    INCBIN "gfx/icons/jellyfish.2bpp"
GeodudeIcon:      INCBIN "gfx/icons/geodude.2bpp"
PonytaIcon:       INCBIN "gfx/icons/ponyta.2bpp"
SlowpokeIcon:     INCBIN "gfx/icons/slowpoke.2bpp"
MagnemiteIcon:    INCBIN "gfx/icons/magnemite.2bpp"
Farfetch_dIcon:   INCBIN "gfx/icons/farfetch_d.2bpp"
SeelIcon:         INCBIN "gfx/icons/seel.2bpp"
BlobIcon:         INCBIN "gfx/icons/blob.2bpp"
DittoIcon:        INCBIN "gfx/icons/ditto.2bpp"
ShellIcon:        INCBIN "gfx/icons/shell.2bpp"
GastlyIcon:       INCBIN "gfx/icons/gastly.2bpp"
GhostIcon:        INCBIN "gfx/icons/ghost.2bpp"
SerpentIcon:      INCBIN "gfx/icons/serpent.2bpp"
HumanshapeIcon:   INCBIN "gfx/icons/humanshape.2bpp"
KrabbyIcon:       INCBIN "gfx/icons/krabby.2bpp"
SudowoodoIcon:    INCBIN "gfx/icons/sudowoodo.2bpp"
ChanseyIcon:      INCBIN "gfx/icons/chansey.2bpp"
TangelaIcon:      INCBIN "gfx/icons/tangela.2bpp"
HorseaIcon:       INCBIN "gfx/icons/horsea.2bpp"
StaryuIcon:       INCBIN "gfx/icons/staryu.2bpp"
ScytherIcon:      INCBIN "gfx/icons/scyther.2bpp"
; BigmonIcon:       INCBIN "gfx/icons/bigmon.2bpp"
TaurosIcon:       INCBIN "gfx/icons/tauros.2bpp"
FishIcon:         INCBIN "gfx/icons/fish.2bpp"
GyaradosIcon:     INCBIN "gfx/icons/gyarados.2bpp"
LaprasIcon:       INCBIN "gfx/icons/lapras.2bpp"
EeveeIcon:        INCBIN "gfx/icons/eevee.2bpp"
Porygon2Icon:     INCBIN "gfx/icons/porygon2.2bpp"
SnorlaxIcon:      INCBIN "gfx/icons/snorlax.2bpp"
ArticunoIcon:     INCBIN "gfx/icons/articuno.2bpp"
ZapdosIcon:       INCBIN "gfx/icons/zapdos.2bpp"
MoltresIcon:      INCBIN "gfx/icons/moltres.2bpp"
MewtwoIcon:       INCBIN "gfx/icons/mewtwo.2bpp"
MewIcon:          INCBIN "gfx/icons/mew.2bpp"
TangelIcon:       INCBIN "gfx/icons/tangel.2bpp"
BearIcon:         INCBIN "gfx/icons/bear.2bpp"
WolfrostIcon:     INCBIN "gfx/icons/wolfrost.2bpp"
ChikoritaIcon:    INCBIN "gfx/icons/chikorita.2bpp"
MeganiumIcon:     INCBIN "gfx/icons/meganium.2bpp"
CyndaquilIcon:    INCBIN "gfx/icons/cyndaquil.2bpp"
TyphlosionIcon:   INCBIN "gfx/icons/typhlosion.2bpp"
TotodileIcon:     INCBIN "gfx/icons/totodile.2bpp"
FeraligatrIcon:   INCBIN "gfx/icons/feraligatr.2bpp"
SentretIcon:      INCBIN "gfx/icons/sentret.2bpp"
BirdIcon:         INCBIN "gfx/icons/bird.2bpp"
LedianIcon:       INCBIN "gfx/icons/ledian.2bpp"
JoltikIcon:       INCBIN "gfx/icons/joltik.2bpp"
ChinchouIcon:     INCBIN "gfx/icons/chinchou.2bpp"
TogepiIcon:       INCBIN "gfx/icons/togepi.2bpp"
FlaaffyIcon:      INCBIN "gfx/icons/flaaffy.2bpp"
YanmaIcon:        INCBIN "gfx/icons/yanma.2bpp"
UnownIcon:        INCBIN "gfx/icons/unown.2bpp"
GirafarigIcon:    INCBIN "gfx/icons/girafarig.2bpp"
FerroseedIcon:    INCBIN "gfx/icons/ferroseed.2bpp"
DunsparceIcon:    INCBIN "gfx/icons/dunsparce.2bpp"
GligarIcon:       INCBIN "gfx/icons/gligar.2bpp"
ShuckleIcon:      INCBIN "gfx/icons/shuckle.2bpp"
SneaselIcon:      INCBIN "gfx/icons/sneasel.2bpp"
SlugmaIcon:       INCBIN "gfx/icons/slugma.2bpp"
SwinubIcon:       INCBIN "gfx/icons/swinub.2bpp"
CorsolaIcon:      INCBIN "gfx/icons/corsola.2bpp"
OctilleryIcon:    INCBIN "gfx/icons/octillery.2bpp"
MantineIcon:      INCBIN "gfx/icons/mantine.2bpp"
DonphanIcon:      INCBIN "gfx/icons/donphan.2bpp"
MiltankIcon:      INCBIN "gfx/icons/miltank.2bpp"
RaikouIcon:       INCBIN "gfx/icons/raikou.2bpp"
EnteiIcon:        INCBIN "gfx/icons/entei.2bpp"
SuicuneIcon:      INCBIN "gfx/icons/suicune.2bpp"
LugiaIcon:        INCBIN "gfx/icons/lugia.2bpp"
Ho_ohIcon:        INCBIN "gfx/icons/ho_oh.2bpp"
CelebiIcon:       INCBIN "gfx/icons/celebi.2bpp"
TreeckoIcon:      INCBIN "gfx/icons/treecko.2bpp"
SceptileIcon:     INCBIN "gfx/icons/sceptile.2bpp"
TorchicIcon:      INCBIN "gfx/icons/torchic.2bpp"
BlazikenIcon:     INCBIN "gfx/icons/blaziken.2bpp"
MudkipIcon:       INCBIN "gfx/icons/mudkip.2bpp"
SwampertIcon:     INCBIN "gfx/icons/swampert.2bpp"
ZigzagoonIcon:    INCBIN "gfx/icons/zigzagoon.2bpp"
LotadIcon:        INCBIN "gfx/icons/lotad.2bpp"
WingullIcon:      INCBIN "gfx/icons/wingull.2bpp"
GardevoirIcon:    INCBIN "gfx/icons/gardevoir.2bpp"
ShroomishIcon:    INCBIN "gfx/icons/shroomish.2bpp"
MakuhitaIcon:     INCBIN "gfx/icons/makuhita.2bpp"
NosepassIcon:     INCBIN "gfx/icons/nosepass.2bpp"
MawileIcon:       INCBIN "gfx/icons/mawile.2bpp"
RoseliaIcon:      INCBIN "gfx/icons/roselia.2bpp"
WailmerIcon:      INCBIN "gfx/icons/wailmer.2bpp"
NumelIcon:        INCBIN "gfx/icons/numel.2bpp"
AltariaIcon:      INCBIN "gfx/icons/altaria.2bpp"
CarbinkIcon:      INCBIN "gfx/icons/carbink.2bpp"
BaltoyIcon:       INCBIN "gfx/icons/baltoy.2bpp"
ChimechoIcon:     INCBIN "gfx/icons/chimecho.2bpp"
SnoruntIcon:      INCBIN "gfx/icons/snorunt.2bpp"
TyruntIcon:       INCBIN "gfx/icons/tyrunt.2bpp"
ShelgonIcon:      INCBIN "gfx/icons/shelgon.2bpp"
; MetangIcon:       INCBIN "gfx/icons/metang.2bpp"
; RegiIcon:         INCBIN "gfx/icons/regi.2bpp"
LatiasIcon:       INCBIN "gfx/icons/latias.2bpp"
; KyogreIcon:       INCBIN "gfx/icons/kyogre.2bpp"
GroudonIcon:      INCBIN "gfx/icons/groudon.2bpp"
; RayquazaIcon:     INCBIN "gfx/icons/rayquaza.2bpp"
; JirachiIcon:      INCBIN "gfx/icons/jirachi.2bpp"
DeoxysIcon:       INCBIN "gfx/icons/deoxys.2bpp"


SECTION "Mon Icons 2", ROMX

TurtwigIcon:      INCBIN "gfx/icons/turtwig.2bpp"
ChimcharIcon:     INCBIN "gfx/icons/chimchar.2bpp"
PiplupIcon:       INCBIN "gfx/icons/piplup.2bpp"
DrifloonIcon:     INCBIN "gfx/icons/drifloon.2bpp"
ChinglingIcon:    INCBIN "gfx/icons/chingling.2bpp"
BronzorIcon:      INCBIN "gfx/icons/bronzor.2bpp"
HaxorusIcon:      INCBIN "gfx/icons/haxorus.2bpp"
LucarioIcon:      INCBIN "gfx/icons/lucario.2bpp"
CroagunkIcon:     INCBIN "gfx/icons/croagunk.2bpp"
; MespritIcon:      INCBIN "gfx/icons/mesprit.2bpp"
AurorusIcon:      INCBIN "gfx/icons/aurorus.2bpp"
; ShayminIcon:      INCBIN "gfx/icons/shaymin.2bpp"
ArceusIcon:       INCBIN "gfx/icons/arceus.2bpp"
RockruffIcon:     INCBIN "gfx/icons/rockruff.2bpp"
VenonatIcon:      INCBIN "gfx/icons/venonat.2bpp"
MankeyIcon:       INCBIN "gfx/icons/mankey.2bpp"
ExeggcuteIcon:    INCBIN "gfx/icons/exeggcute.2bpp"
KoffingIcon:      INCBIN "gfx/icons/koffing.2bpp"
ElectabuzzIcon:   INCBIN "gfx/icons/electabuzz.2bpp"
VikavoltIcon:     INCBIN "gfx/icons/vikavolt.2bpp"
OmanyteIcon:      INCBIN "gfx/icons/omanyte.2bpp"
LuvdiscIcon:      INCBIN "gfx/icons/luvdisc.2bpp"
SharpedoIcon:     INCBIN "gfx/icons/sharpedo.2bpp"
HoothootIcon:     INCBIN "gfx/icons/hoothoot.2bpp"
MareepIcon:       INCBIN "gfx/icons/mareep.2bpp"
AmpharosIcon:     INCBIN "gfx/icons/ampharos.2bpp"
MarillIcon:       INCBIN "gfx/icons/marill.2bpp"
WooperIcon:       INCBIN "gfx/icons/wooper.2bpp"
QuagsireIcon:     INCBIN "gfx/icons/quagsire.2bpp"
MurkrowIcon:      INCBIN "gfx/icons/murkrow.2bpp"
ShuppetIcon:      INCBIN "gfx/icons/shuppet.2bpp"
GranbullIcon:     INCBIN "gfx/icons/granbull.2bpp"
HeracrossIcon:    INCBIN "gfx/icons/heracross.2bpp"
PhanpyIcon:       INCBIN "gfx/icons/phanpy.2bpp"
SmeargleIcon:     INCBIN "gfx/icons/smeargle.2bpp"
LarvitarIcon:     INCBIN "gfx/icons/larvitar.2bpp"
PupitarIcon:      INCBIN "gfx/icons/pupitar.2bpp"
TyranitarIcon:    INCBIN "gfx/icons/tyranitar.2bpp"
PelipperIcon:     INCBIN "gfx/icons/pelipper.2bpp"
AronIcon:         INCBIN "gfx/icons/aron.2bpp"
; TorkoalIcon:      INCBIN "gfx/icons/torkoal.2bpp"
; GrumpigIcon:      INCBIN "gfx/icons/grumpig.2bpp"
TrapinchIcon:     INCBIN "gfx/icons/trapinch.2bpp"
FlygonIcon:       INCBIN "gfx/icons/flygon.2bpp"
ZangooseIcon:     INCBIN "gfx/icons/zangoose.2bpp"
LunatoneIcon:     INCBIN "gfx/icons/lunatone.2bpp"
SolrockIcon:      INCBIN "gfx/icons/solrock.2bpp"
ClaydolIcon:      INCBIN "gfx/icons/claydol.2bpp"
LileepIcon:       INCBIN "gfx/icons/lileep.2bpp"
DuskullIcon:      INCBIN "gfx/icons/duskull.2bpp"
DusclopsIcon:     INCBIN "gfx/icons/dusclops.2bpp"
TropiusIcon:      INCBIN "gfx/icons/tropius.2bpp"
AbsolIcon:        INCBIN "gfx/icons/absol.2bpp"
GlalieIcon:       INCBIN "gfx/icons/glalie.2bpp"
SphealIcon:       INCBIN "gfx/icons/spheal.2bpp"
SalamenceIcon:    INCBIN "gfx/icons/salamence.2bpp"
; BeldumIcon:       INCBIN "gfx/icons/beldum.2bpp"
; MetagrossIcon:    INCBIN "gfx/icons/metagross.2bpp"
FloatzelIcon:     INCBIN "gfx/icons/floatzel.2bpp"
BronzongIcon:     INCBIN "gfx/icons/bronzong.2bpp"
TogekissIcon:     INCBIN "gfx/icons/togekiss.2bpp"
DewottIcon:       INCBIN "gfx/icons/dewott.2bpp"
MunnaIcon:        INCBIN "gfx/icons/munna.2bpp"
ScolipedeIcon:    INCBIN "gfx/icons/scolipede.2bpp"
KrookodileIcon:   INCBIN "gfx/icons/krookodile.2bpp"
; ArchenIcon:       INCBIN "gfx/icons/archen.2bpp"
SolosisIcon:      INCBIN "gfx/icons/solosis.2bpp"
LitwickIcon:      INCBIN "gfx/icons/litwick.2bpp"
ChandelureIcon:   INCBIN "gfx/icons/chandelure.2bpp"
AxewIcon:         INCBIN "gfx/icons/axew.2bpp"
; GolurkIcon:       INCBIN "gfx/icons/golurk.2bpp"
HeatmorIcon:      INCBIN "gfx/icons/heatmor.2bpp"
; DeinoIcon:        INCBIN "gfx/icons/deino.2bpp"
; ZweilousIcon:     INCBIN "gfx/icons/zweilous.2bpp"
; HydreigonIcon:    INCBIN "gfx/icons/hydreigon.2bpp"
SpewpaIcon:       INCBIN "gfx/icons/spewpa.2bpp"
; VolcaronaIcon:    INCBIN "gfx/icons/volcarona.2bpp"
ChespinIcon:      INCBIN "gfx/icons/chespin.2bpp"
ChesnaughtIcon:   INCBIN "gfx/icons/chesnaught.2bpp"
FennekinIcon:     INCBIN "gfx/icons/fennekin.2bpp"
DelphoxIcon:      INCBIN "gfx/icons/delphox.2bpp"
FroakieIcon:      INCBIN "gfx/icons/froakie.2bpp"
GreninjaIcon:     INCBIN "gfx/icons/greninja.2bpp"
FloetteIcon:      INCBIN "gfx/icons/floette.2bpp"
GogoatIcon:       INCBIN "gfx/icons/gogoat.2bpp"
EspurrIcon:       INCBIN "gfx/icons/espurr.2bpp"
HonedgeIcon:      INCBIN "gfx/icons/honedge.2bpp"
InkayIcon:        INCBIN "gfx/icons/inkay.2bpp"
DedenneIcon:      INCBIN "gfx/icons/dedenne.2bpp"
GoodraIcon:       INCBIN "gfx/icons/goodra.2bpp"
; KlefkiIcon:       INCBIN "gfx/icons/klefki.2bpp"
BergmiteIcon:     INCBIN "gfx/icons/bergmite.2bpp"
; XerneasIcon:      INCBIN "gfx/icons/xerneas.2bpp"
; YveltalIcon:      INCBIN "gfx/icons/yveltal.2bpp"
; ZygardeIcon:      INCBIN "gfx/icons/zygarde.2bpp"
; VolcanionIcon:    INCBIN "gfx/icons/volcanion.2bpp"
RowletIcon:       INCBIN "gfx/icons/rowlet.2bpp"
DecidueyeIcon:    INCBIN "gfx/icons/decidueye.2bpp"
RibombeeIcon:     INCBIN "gfx/icons/ribombee.2bpp"
SnivyIcon:        INCBIN "gfx/icons/snivy.2bpp"
MudsdaleIcon:     INCBIN "gfx/icons/mudsdale.2bpp"
MorelullIcon:     INCBIN "gfx/icons/morelull.2bpp"
AipomIcon:        INCBIN "gfx/icons/aipom.2bpp"
SandygastIcon:    INCBIN "gfx/icons/sandygast.2bpp"
PyukumukuIcon:    INCBIN "gfx/icons/pyukumuku.2bpp"
; TypeNullIcon:    INCBIN "gfx/icons/type_null.2bpp"
; SilvallyIcon:     INCBIN "gfx/icons/silvally.2bpp"
TogedemaruIcon:   INCBIN "gfx/icons/togedemaru.2bpp"
DhelmiseIcon:     INCBIN "gfx/icons/dhelmise.2bpp"
; Hakamo_oIcon:     INCBIN "gfx/icons/hakamo_o.2bpp"
; NihilegoIcon:     INCBIN "gfx/icons/nihilego.2bpp"
; BuzzwoleIcon:     INCBIN "gfx/icons/buzzwole.2bpp"
; PheromosaIcon:    INCBIN "gfx/icons/pheromosa.2bpp"
; XurkitreeIcon:    INCBIN "gfx/icons/xurkitree.2bpp"
; CelesteelaIcon:   INCBIN "gfx/icons/celesteela.2bpp"
; KartanaIcon:      INCBIN "gfx/icons/kartana.2bpp"
; GuzzlordIcon:     INCBIN "gfx/icons/guzzlord.2bpp"
; MagearnaIcon:     INCBIN "gfx/icons/magearna.2bpp"
; StakatakaIcon:    INCBIN "gfx/icons/stakataka.2bpp"
; BlacephalonIcon:  INCBIN "gfx/icons/blacephalon.2bpp"
ApplinIcon:       INCBIN "gfx/icons/applin.2bpp"
SizzlipedeIcon:   INCBIN "gfx/icons/sizzlipede.2bpp"
ClobbopusIcon:    INCBIN "gfx/icons/clobbopus.2bpp"
PolteageistIcon:  INCBIN "gfx/icons/polteageist.2bpp"
BlastoiseIcon:    INCBIN "gfx/icons/blastoise.2bpp"
SandshrewIcon:    INCBIN "gfx/icons/sandshrew.2bpp"
NidokingIcon:     INCBIN "gfx/icons/nidoking.2bpp"
DoduoIcon:        INCBIN "gfx/icons/doduo.2bpp"
CuboneIcon:       INCBIN "gfx/icons/cubone.2bpp"
RhyhornIcon:      INCBIN "gfx/icons/rhyhorn.2bpp"
MagmarIcon:       INCBIN "gfx/icons/magmar.2bpp"
PinsirIcon:       INCBIN "gfx/icons/pinsir.2bpp"
FurretIcon:       INCBIN "gfx/icons/furret.2bpp"
TogeticIcon:      INCBIN "gfx/icons/togetic.2bpp"
MisdreavusIcon:   INCBIN "gfx/icons/misdreavus.2bpp"
WobbuffetIcon:    INCBIN "gfx/icons/wobbuffet.2bpp"
SkarmoryIcon:     INCBIN "gfx/icons/skarmory.2bpp"
StantlerIcon:     INCBIN "gfx/icons/stantler.2bpp"
ShiftryIcon:      INCBIN "gfx/icons/shiftry.2bpp"
RaltsIcon:        INCBIN "gfx/icons/ralts.2bpp"
MasquerainIcon:   INCBIN "gfx/icons/masquerain.2bpp"
GulpinIcon:       INCBIN "gfx/icons/gulpin.2bpp"
MiloticIcon:      INCBIN "gfx/icons/milotic.2bpp"
WalreinIcon:      INCBIN "gfx/icons/walrein.2bpp"
PigniteIcon:      INCBIN "gfx/icons/pignite.2bpp"
; TynamoIcon:       INCBIN "gfx/icons/tynamo.2bpp"
ElgyemIcon:       INCBIN "gfx/icons/elgyem.2bpp"
LampentIcon:      INCBIN "gfx/icons/lampent.2bpp"
MienshaoIcon:     INCBIN "gfx/icons/mienshao.2bpp"
; DruddigonIcon:    INCBIN "gfx/icons/druddigon.2bpp"
FletchlingIcon:   INCBIN "gfx/icons/fletchling.2bpp"
; FlabebeIcon:      INCBIN "gfx/icons/flabebe.2bpp"
FlorgesIcon:      INCBIN "gfx/icons/florges.2bpp"
SpritzeeIcon:     INCBIN "gfx/icons/spritzee.2bpp"
AromatisseIcon:   INCBIN "gfx/icons/aromatisse.2bpp"
HawluchaIcon:     INCBIN "gfx/icons/hawlucha.2bpp"
PumpkabooIcon:    INCBIN "gfx/icons/pumpkaboo.2bpp"
GourgeistIcon:    INCBIN "gfx/icons/gourgeist.2bpp"
OranguruIcon:     INCBIN "gfx/icons/oranguru.2bpp"